import { Inter } from "next/font/google";
import "./globals.css";
import ReduxWrapper from "@/redux/ReduxWrapper";
// import NavBar from "@/components/navbar/NavBar";
import NavBar from "./_components/navbar/NavBar";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocalRootLayout({ children, params }) {
  const messages = useMessages();

  return (
    <html lang={params.locale}>
      <ReduxWrapper>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <body className={inter.className}>
            <NavBar />
            {children}
          </body>
        </NextIntlClientProvider>
      </ReduxWrapper>
    </html>
  );
}
